{% set name = "adstex" %}
{% set version = "0.3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adstex-{{ version }}.tar.gz
  sha256: bb88ef2605df188255266ace705484eba2d414543f6de58ca7bd0a3f2cc196b8

build:
  number: 0
  noarch: python
  entry_points:
    - adstex=adstex:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ads >=0.12.3
    - bibtexparser >=0.6.2
    - python >=3.6
    - requests >=2.0

test:
  imports:
    - adstex
  commands:
    - pip check
    - adstex --help
  requires:
    - pip

about:
  home: https://github.com/yymao/adstex
  summary: Find all citation keys in your LaTeX documents and search NASA ADS to generate corresponding bibtex entries.
  license: MIT
  # License file manually packaged for version <= 0.3.8. Future releases would include LICENSE in source tarball.
  license_file: LICENSE
  doc_url: https://github.com/yymao/adstex/blob/master/README.md
  dev_url: https://github.com/yymao/adstex

extra:
  recipe-maintainers:
    - yymao
