{% set name = "adstex" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adstex-{{ version }}.tar.gz
  sha256: 8619fbe53e7f52b579696dac9f844463d370c3d1463908bff885933e70a8e1d9

build:
  number: 0
  noarch: python
  entry_points:
    - adstex=adstex:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ads >=0.12.3
    - bibtexparser >=1.3.0,<2.0.0a0
    - joblib >=1.0
    - packaging >=17.0
    - python >=3.6
    - requests >=2.0

test:
  imports:
    - adstex
  commands:
    - pip check
    - adstex --help
  requires:
    - pip

about:
  home: https://github.com/yymao/adstex
  summary: Find all citation keys in your LaTeX documents and search NASA ADS to generate corresponding bibtex entries.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/yymao/adstex/blob/master/README.md
  dev_url: https://github.com/yymao/adstex

extra:
  recipe-maintainers:
    - yymao
