{% set name = "adstex" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adstex-{{ version }}.tar.gz
  sha256: 48b9dea8a6f8c222d1c7fda5ad43673957de526ac5583f5650d88133ee102e78

build:
  number: 0
  noarch: python
  entry_points:
    - adstex=adstex:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ads >=0.12.3
    - bibtexparser >=1.3.0,<2.0.0a0
    - joblib >=1.0
    - packaging >=17.0
    - python >={{ python_min }}
    - requests >=2.0

test:
  imports:
    - adstex
  commands:
    - pip check
    - adstex --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yymao/adstex
  summary: Find all citation keys in your LaTeX documents and search NASA ADS to generate corresponding bibtex entries.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/yymao/adstex/blob/master/README.md
  dev_url: https://github.com/yymao/adstex

extra:
  recipe-maintainers:
    - yymao
