{% set name = "adstex" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adstex-{{ version }}.tar.gz
  sha256: d335908a2fd64dc7b24f3c740277004cd42cffe388d322796a0577bf97dcbeea

build:
  number: 0
  noarch: python
  entry_points:
    - adstex=adstex:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ads >=0.12.3
    - bibtexparser >=0.6.2
    - packaging >=17.0
    - python >=3.6
    - requests >=2.0

test:
  imports:
    - adstex
  commands:
    - pip check
    - adstex --help
  requires:
    - pip

about:
  home: https://github.com/yymao/adstex
  summary: Find all citation keys in your LaTeX documents and search NASA ADS to generate corresponding bibtex entries.
  license: MIT
  doc_url: https://github.com/yymao/adstex/blob/master/README.md
  dev_url: https://github.com/yymao/adstex

extra:
  recipe-maintainers:
    - yymao
